import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
const M = '/ca.jpg'
const Mcm = '/ca-min.jpg'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>img/color</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <MyImage src={M} placeholderSrc={Mcm} />
      </div>
    </div>
  )
}

const MyImage = ({ src, placeholderSrc, width = '100%', ...props }: any) => {
  const [ImageSrc, setImageSrc] = useState(placeholderSrc)
  const style = `progresive ${
    ImageSrc === placeholderSrc ? 'loading' : 'loaded'
  }`
  useEffect(() => {
    const image = new Image()
    image.src = src
    image.onload = () => {
      setImageSrc(src)
    }
  }, [src])
  return (
    <div>
      <img
        className={style}
        src={ImageSrc}
        alt='alt'
        height={'100%'}
        width='100%'
      />
      <div>
        <h1 style={{color: 'pink'}}>di</h1>
      </div>
    </div>
  )
}

export default Home
